### PR TITLE
Low hanging lint changes

### PR DESCRIPTION
**Pull request by djdv**
I ran `gometalinter` while making some changes, it caught several actual issues related to Errorf calls, and made some simplification suggestions, there is also a single change to conform to error conventions (don't end in a period).
I committed the suggested changes excluding: warnings about shadowing vars, documentation, and permission/security settings. I don't plan on addressing those.

### CODE REVIEW

**Comment by djdv** [comment]
I don't know what's going on with Travis （ ´_ゝ｀）

**Comment by djdv** [comment]
I think it was failing because of the old Go version. Rebased and it's fine now.
ping @whyrusleeping

**Comment by whyrusleeping** [comment]
Thanks @djdv :)

**Comment by djdv** [comment]
My bad. 😬
https://github.com/whyrusleeping/gx/pull/156

Will this impact the repo size in a way that needs intervention?

**Pull request merged**
