### PR TITLE
Mention IPFS_PATH

### PR DESCRIPTION
**Pull request by anacrolix**
Related to #230.

### CODE REVIEW

**Comment by Stebalien** [comment]
`IPFS_PATH` isn't actually _necessary_ unless your repo is in a non-standard location (in which case you will have already set `IPFS_PATH` somewhere).

**Comment by anacrolix** [comment]
"may be necessary" is too dubious?

**Comment by Stebalien** [comment]
To vague, IMO. We could say something like:

> If your IPFS repo is in a non-standard location, remember to set `$IPFS_PATH`. Alternatively, you can explicitly set `$IPFS_API` to `$IPFS_API_IPADDR:$PORT`.

**Comment by anacrolix** [comment]
Yeah it's much better.

**Pull request merged**
