### PR TITLE
rename package.json fields

### PR DESCRIPTION
**Pull request by slang800**
This PR changes `issues_url` to `bugs` and `gx_version` to `gxVersion`.

The first change is because package.json files used in npm projects use the [bugs field](https://docs.npmjs.com/files/package.json#bugs) to hold the same information that your `issues_url` field holds. I think that it's worthwhile to copy this convention because it will make transitioning from npm to gx easier and will let us reuse some of the tooling that has been built for npm package.json files.

The second change is because camelCase is normally used in JSON, including the `gxDependencies` field and fields within npm's package.json files. I think that it's a good idea to remain consistent and not introduce snake_case to JSON field naming.

### CODE REVIEW

**Comment by sterpe** [comment]
So now all gx packages have to be republished?

**Comment by slang800** [comment]
Yeah. We could write code to fix them automatically or maintain backwards compatibility, but given that gx is still in alpha, I doubt that it would be worth it. Also, considering the number of packages that are published within npm, it would be much easier to change the gx packages than convince all npm packages to change their fields for compatibility.

**Comment by whyrusleeping** [comment]
I think writing a small shim for forwards compatibility might be easy enough. I'm not hugely worried about backwards compatiblity (we can have a message telling people to upgrade their gx).

This will take a little bit longer to figure out though, so bear with me!

**Comment by whyrusleeping** [comment]
oh wait, misread initially. This just changes `gx_version` and not the dependencies field. This should be pretty simple

**Comment by slang800** [comment]
Yeah, just `gx_version` and `issues_url`.

Changing `gxDependencies` to `dependencies` might be a good idea, but that would require quite a bit of thought & discussion since npm doesn't have a direct equivalent... That would be best saved for a separate issue.

**Comment by sterpe** [comment]
@whyrusleeping i noticed that I can't 'gx init' a repo which already has a package.json, such as a node module transitioning to gx from npm.  Is it on the roadmap to append gx fields to existing package.json?  Should I put together PR for this?

**Comment by whyrusleeping** [comment]
@sterpe Yeah, I do like the idea of having the fields of an npm package.json and a gx package.json combined. We should probably think about that some, feel free to PR something so we can discuss

**Comment by whyrusleeping** [comment]
alright, this LGTM. Thanks @slang800 !

**Pull request merged**
