### PR TITLE
Correct spelling and punctuation in version help

### PR DESCRIPTION
**Pull request by adamnovak**
In general it looks like the help writing style needs to be standardized. When are we using capitalization? When are we using complete sentences? Should there always be an EXAMPLES section?

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@RichardLitt is who I was going to ask about a general style guide. 

For capitalization, I think that at the beginning of sentences is fine for the long help text, but for the usage string, I feel like everything should be lowercase (if you disagree, let me know). 

I think an examples section should be added whenever possible (so probably for every command), Where they are missing is mostly just laziness on my part.

**Comment by whyrusleeping** [comment]
If you want to make changes to this PR, i'll leave it open, otherwise i'll go ahead and merge

**Comment by adamnovak** [comment]
I think this one should stand as is; revising everything to fit the style
can wait until I have more time.

**Comment by whyrusleeping** [comment]
Cool, thanks for the PR!

**Comment by RichardLitt** [comment]
Yeah, that can be done later. +1 for this.

**Pull request merged**
