### PR TITLE
Add update-tree command

### PR DESCRIPTION
**Pull request by lgierth**
Which updates certain packages in a workspace tree of packages, and bubbles up the changed hash through all dependents in the workspace.

It does work, but is really slow (it seems to be `PublishPackage()` that's slow), and needs a bit more determinism.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
(before i really read through the code)

What exactly is the process it goes through here? How does it find 'myPkg' and 'otherPkg' , is it by hash? or just the first package where name == 'myPkg' ?

Does it touch *every* package in ~/workspace that imports 'myPkg' or 'otherPkg' ? Which version does it update them to?

**Comment by lgierth** [comment]
I pushed another update and it looks like it works nicely now. I also added command docs which briefly explain the process.

> What exactly is the process it goes through here?

1. Scan '~/workspace' for packages, i.e. directories with a package.json file.
2. Publish 'myPkg' and 'otherPkg'.
3. Update the hashes in packages which depend on 'myPkg' or 'otherPkg'.
4. Publish these updated packages.
5. Update their respective dependent packages.
6. And so on.

Sample output from a ipfs+libp2p+multiformats organizations workspace: https://ipfs.io/ipfs/QmPzQwYMYQvNEedA8Uu1AwEMTbBRA9PvpYmM4X3MNXB5iA

> How does it find 'myPkg' and 'otherPkg' , is it by hash? or just the first package where name == 'myPkg' ?

the latter -- It doesn't fetch anything from ipfs

> Does it touch every package in ~/workspace that imports 'myPkg' or 'otherPkg' ?

Every package that has myPkg or otherPkg somewhere in its dependency tree. Or rather, in the dependency tree subset which is available in the workspace directory.

> Which version does it update them to?

It publishes the current state of the package directory and uses that hash. We should definitely bump the version, but I haven't figured out yet how to do that only once per package.

We should probably also gx-install the published packages, right now you have to manually run `gx install` after a `gx update-tree`.

**Comment by lgierth** [comment]
> Every package that has myPkg or otherPkg somewhere in its dependency tree. Or rather, in the dependency tree subset which is available in the workspace directory.

An example for this is how go-utp-transport isn't depended on by e.g. go-ipfs, but still gets it's dependencies update because go-multiaddr changed.

**Comment by whyrusleeping** [comment]
How does it deal with multiple packages that have the same name?

**Comment by lgierth** [comment]
I haven't taken that into account, but the last one (based on `ioutil.ReadDir()`) wins. It only scans the workspace once and then should be consistent.

**Comment by whyrusleeping** [comment]
> We should probably also gx-install the published packages, right now you have to manually run gx install after a gx update-tree.

Yeah, i've considered adding 'install new package' as a post-publish step

**Comment by lgierth** [comment]
> Every package that has myPkg or otherPkg somewhere in its dependency tree. Or rather, in the dependency tree subset which is available in the workspace directory.

While the wip workspace script at ipfs/community#179 currently only clones ipfs+libp2p+multiformats, we could have it clone all dependencies (based on hash+dvcsimportpath)

**Comment by Kubuxu** [comment]
I think it needs filter file or filter expression, I used to symlink repos into Golang  tress but it causes sometimes more problems than solutions. Now I have just one enormous tree.

Other solution would be: propagate update of package X for package Y, then it would scan dependencies of package Y and update them recursively with package X.

**Comment by lgierth** [comment]
Okay I updated this a bit more. It now also bumps the version and installs the fresh package, but doesn't commit for now.

You should be able to try it out with setting up a workspace/myrepos config, but it's handy to do so since you can run the same command on all packages in one go, e.g. `mr run git checkout .` to reset the update procedure, or commit and file the pull request.

1. workspace config
```sh
> sudo apt-get install myrepos && go get github.com/github/hub
> cd $GOPATH/src/github.com
> ./mkmrconfig.sh > .mrconfig # see [1]
> mr checkout
> mr status
> gx update-tree `pwd` go-multihash
> mr status
> mr -j 5 run 'git checkout -b feat/update-deps && git commit -am "gx release 6.6.6" && git push origin feat/update-deps'
> mr run 'hub pull-request -m "Update deps and release"'
```

[1] https://raw.githubusercontent.com/ipfs/community/a87d3c684fd2b24da717aa80a85d8488cc65dfae/dev/tools/myrepos/mkmrconfig.sh

Known issues
- lacks automatic setup of the workspace
- lacks final collective commit+push+pr
- version inconsistencies in different packagejsons
  - but that's an issue in these packages, not in gx itself
- awful error message when daemon isn't running
  - object/new: 1: This command can't be called directly. Try one of its subcommands.

**Comment by lgierth** [comment]
Closing in favor of #109

**Pull request closed without merging**
