### PR TITLE
test: fix: "install output looks good", added hash

### PR DESCRIPTION
**Pull request by schomatis**
Fixes test bug introduced in non-PR commit.

### CODE REVIEW

**Comment by Stebalien** [comment]
Still seems a bit off.

**Comment by schomatis** [comment]
Yes, the elapsed time is missing (I haven't updated my `progmeter` repo), can a wildcard be used there (e.g., `.*?s`)? Adding a special time regex seems a bit error prone.

**Comment by Stebalien** [comment]
Maybe something like `^\[done\]\s\+\[install\]\s\+[0-9]\+[a-z]\+\s\+...`?

**Comment by schomatis** [comment]
Not sure I follow, which is the part for the elapsed time, `[0-9]\+[a-z]\+`?

Right now the `grep` regex is something like:

```
grep "\[done\] \[install\] $pkgA a"
```

but the `gx` output with new format has an elapsed time like

```
[done] [install] 0s    Qmemb8MUvUJC1VRDh8NrpovYJCEGXFfyXGbxccabXXY8G9 b
```

(although that time is usually `0s`), what do you recommend to add to the `grep` to account for the time string?

**Comment by Stebalien** [comment]
Yes, that was the `[0-9]\+[a-z]\+` part. The other parts were to deal with the variable spacing.

**Comment by schomatis** [comment]
Ok, I'll add a possible decimal part to the number, but I fear the resulting regex will be harder to read only to accommodate the not-very-relevant time part of the output.

**Comment by schomatis** [comment]
Yes, that seems better, but I can't get it to work, I'm trying
```
grep "\[done\] \[install\] [^\s]\+\s\+$pkgA a" install_out
```
I'm not sure what I'm doing wrong here (I'm definitely missing something), but I'd rather don't spend more time on this issue, let's leave like this.

**Pull request merged**
