### PR TITLE
Gx could not locate the local ipfs daemon on Windows

### PR DESCRIPTION
**Pull request by kalmi**
There is no HOME env var on Windows. We could use mitchellh's go-homedir library to find the home directory.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@kalmi this sounds good to me, wanna adjust the other similar calls too? 
```
./gxutil/repo.go:  
65:	home := os.Getenv("HOME") 
  
./gxutil/repo.go:  
91:	home := os.Getenv("HOME") 
  
./gxutil/config.go:  
43:	cfg, err := loadFile(path.Join(os.Getenv("HOME"), CfgFileName)) 
  
./gxutil/shell.go:  
28:		home := os.Getenv("HOME") 
  
./repo.go:  
17:		home := os.Getenv("HOME") 
```

**Comment by kalmi** [comment]
Sure

**Comment by kalmi** [comment]
Done

**Comment by whyrusleeping** [comment]
@kalmi those changes don't build

**Comment by kalmi** [comment]
I am really sorry about that. I am quite new to golang and its build system, and it seems that I ended up  rebuilding only the top-level package and then assuming that all is well. Really sorry about that.

I force pushed a fixed commit. It should build now.

**Comment by whyrusleeping** [comment]
closed in #40, I pulled your changes into there

**Pull request closed without merging**
