### PR TITLE
improve install UI a bit

### PR DESCRIPTION
**Pull request by whyrusleeping**
I would love it if anyone would try this out and provide feedback

### CODE REVIEW

**Comment by whyrusleeping** [comment]
cc @lgierth @Kubuxu

**Comment by noffle** [comment]
I took this for a spin and installed the latest `go-ipfs` deps.

This looks great! I found the output to be very readable compared to the old output style. It'd be great to see this output when doing one-off installs too (`gx install foobar`). I'd be jazzed to see this in master. :+1:

**Comment by Kubuxu** [comment]
Tested it, seems to work. Only thing I am afraid is console capture behaviour.

**Comment by whyrusleeping** [comment]
@noffle thanks! Yeah, i'll add it to more things too.

@Kubuxu perhaps we could output a 'simple' format if the stdout isnt a tty?

**Comment by whyrusleeping** [comment]
@lgierth tests are green, i think i'm gonna merge this. Any objections?

**Pull request merged**
